### ISSUE TITLE
Rsquared()

### ISSUE THREAD

**Issue by mtva0001** [TheoreticalEcology/s-jSDM#90] opened 2022-01-12 12:33 UTC
Hi,

I try to use the Rsquared function but it somehow fails. How could I make it work?

> model2$spatial
~0 + .
<environment: 0x7fbd9b72ecf0>
> R2 = Rsquared(model2)
Error in eval(mf[4]$spatial_formula, envir = parent.env(environment())) : 
  object 'spatial_formula' not found

Many thanks for your help in advance!
/Máté

**Comment by MaximilianPi** [comment] 2022-01-12 13:26
Hi Máté,

thanks for reporting...

I pushed a fix into the devel branch:

`devtools::install_github("https://github.com/TheoreticalEcology/s-jSDM", subdir = "sjSDM", ref = "devel")
`
Cheers,
Max

**Comment by mtva0001** [comment] 2022-01-12 18:02
Now it caused another error:

> R2 = Rsquared(model2)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AssertionError: Size mismatch between tensors

Detailed traceback:
  File "/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sjSDM/python/sjSDM_py/model_sjSDM.py", line 336, in fit
    dataLoader = self._get_DataLoader(X, Y, SP, batch_size, True, parallel)
  File "/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sjSDM/python/sjSDM_py/model_sjSDM.py", line 226, in _get_DataLoader
    torch.tensor(SP, dtype=self.dtype, device=torch.device('cpu')))
  File "/Users/matevass/Library/r-miniconda/envs/r-sjsdm/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 257, in __init__
    assert all(tensors[0].size(0) == tensor.size(0) for tensor in tensors), "Size mismatch between tensors"
Timing stopped at: 0.002 0 0.002

**Comment by MaximilianPi** [comment] 2022-01-12 18:44
Can you please post the output of `sjSDM::install_diagnostic()`?
I think it is caused by the Null model which uses ~0 for the spatial model, resulting in a matrix with dim (N,0) but I cannot reproduce the error. I have added unit tests for different Rsquared scenarios but no errors, so I assume that it is a version issue.

And can you please run the following code:

```
com = simulate_SDM(env = 3L, species = 7L, sites = 10L)
XY = matrix(rnorm(20), 10, 2)
model = sjSDM(Y = com$response, env = linear(com$env_weights), 
              spatial = linear(XY, ~0+.),
              iter = 50L)
m2 = update(model, spatial_formula = ~0)
m2$model$spatial(sjSDM:::pkg.env$torch$tensor(m2$settings$spatial$X, dtype=sjSDM:::pkg.env$torch$float32))

```

**Comment by mtva0001** [comment] 2022-01-12 18:55
Output of install_diagnostic() (excluded other than r-sjsdm env.):

ENV: r-sjsdm
torch:
# packages in environment at /Users/matevass/Library/r-miniconda/envs/r-sjsdm:
#
# Name                    Version                   Build  Channel
pytorch-ranger            0.1.1                    pypi_0    pypi
torch                     1.10.1                   pypi_0    pypi
torch-optimizer           0.3.0                    pypi_0    pypi
torchaudio                0.10.1                   pypi_0    pypi
torchvision               0.11.2                   pypi_0    pypi

numpy:
# packages in environment at /Users/matevass/Library/r-miniconda/envs/r-sjsdm:
#
# Name                    Version                   Build  Channel
numpy                     1.21.5                   pypi_0    pypi

python:         /Users/matevass/Library/r-miniconda/envs/r-sjsdm/bin/python
libpython:      /Users/matevass/Library/r-miniconda/envs/r-sjsdm/lib/libpython3.7m.dylib
pythonhome:     /Users/matevass/Library/r-miniconda/envs/r-sjsdm:/Users/matevass/Library/r-miniconda/envs/r-sjsdm
version:        3.7.1 | packaged by conda-forge | (default, Mar 13 2019, 05:40:40)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/matevass/Library/r-miniconda/envs/r-sjsdm/lib/python3.7/site-packages/numpy
numpy_version:  1.21.5
torch:          /Users/matevass/Library/r-miniconda/envs/r-sjsdm/lib/python3.7/site-packages/torch

NOTE: Python version was forced by use_python function

     active environment : None
       user config file : /Users/matevass/.condarc
 populated config files : /Users/matevass/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/matevass/Library/r-miniconda  (writable)
      conda av data dir : /Users/matevass/Library/r-miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/matevass/Library/r-miniconda/pkgs
                          /Users/matevass/.conda/pkgs
       envs directories : /Users/matevass/Library/r-miniconda/envs
                          /Users/matevass/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.5 Darwin/20.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False


This is the output of the code:
> m2$model$spatial(sjSDM:::pkg.env$torch$tensor(m2$settings$spatial$X, dtype=sjSDM:::pkg.env$torch$float32))
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]], grad_fn=<MmBackward0>)

**Comment by MaximilianPi** [comment] 2022-01-12 19:06
Looks good, can you please create a minimal reproducible example with the `sjSDM::simulate_SDM` function (like above)?

**Comment by mtva0001** [comment] 2022-01-12 19:48
So with this script it works well:

com = simulate_SDM(env = 3L, species = 7L, sites = 10L)
XYtest = matrix(rnorm(20), 10, 2)
modeltest = sjSDM(Y = com$response, env = linear(com$env_weights), 
              spatial = linear(XYtest, ~0+.),
              iter = 50L)

> Rtest = Rsquared(modeltest)
Iter: 50/50 100%|██████████| [00:00, 76.71it/s, loss=3.61][1] 0.9897994

> Rtest
[1] 0.9897994



Could it be the problem that I tried to run Rsquared() on the model generated before I updated the package? So, do I have to re-run the whole sjSDM() now that I updated it to the 1.0.1 version?

**Comment by MaximilianPi** [comment] 2022-01-12 20:05
Is the model from version 1.0.0 or from before the Rsquared-fix push today? (Or even older?)

Actually it shouldn't matter as long as the model is from 1.0.x since I didn't change the 'sjSDM' object in the devel branch (only the methods). It is strange, the error says that the datasets suddenly have different number of rows.

If the model isn't too big, can you email it to me so I can get to the bottom of it (or via dropbox).

**Comment by mtva0001** [comment] 2022-01-12 20:37
It's the one before the Rsquared-fix. I email it in a minute! Thanks!

**Comment by MaximilianPi** [comment] 2022-01-12 21:03
Okay, I found the problem:

Your data:
env 40 rows + 21 rows with NAs
space 40 rows

This isn't a problem in the full model because the model.matrix removes the NA rows and only 40 rows are used in the model. But for the Rsquared function I have to fit an intercept only model where the NA rows are not dropped, resulting in an env matrix with 61 rows (only intercept) and a space matrix with 40 rows (which causes the error):

![image](https://user-images.githubusercontent.com/29951520/149220148-f72e826a-6aa1-415b-bbdc-e656c5c88372.png)

Quick fix for now:
- re-fit everything but with complete.cases on your environment matrix so that there are no NAs in the matrices
- **or** change the env data object in your model post-hoc:

```
model = readRDS("../../../Downloads/model2.rds")
model$settings$env$data = model$settings$env$data[complete.cases(model$settings$env$data),] # remove NA rows
Rsquared(model, method = "McFadden")
[1] 0.4581529
```

**Comment by mtva0001** [comment] 2022-01-12 21:14
Oh, thanks! I don't know how it happened because I made sure before running the model to remove rows with NAs. I messed something up then. Great that there is a quick post-hoc fix!

**Comment by MaximilianPi** [comment] 2022-01-12 21:35
No, actually it was good that it happened... I need to implement a fix for this behaviour. The user shouldn't have to worry about NAs.

**Closed** 2022-03-11 12:49 UTC
